# NKL Nodeport Service file
# NodePort -ports name must be in the format of
# nkl-<upstream-block-name>
<<<<<<< HEAD
# The nginxinc.io Annotation must be added
=======
>>>>>>> add loadbalancer files
# Chris Akker, Apr 2023
#
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    nginxinc.io/nkl-nginx-lb-http: "stream"    # Must be added
    nginxinc.io/nkl-nginx-lb-https: "stream"   # Must be added
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nkl-nginx-lb-http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: nkl-nginx-lb-https
  selector:
    app: nginx-ingress
