# NKL LoadBalancer Service file
# NodePort -ports name must be in the format of
# nkl-<upstream-block-name>
# externalIPs are set to Nginx LB Servers
# Chris Akker, Jan 2023
#
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  externalIPs:
  - 10.1.1.4
  - 10.1.1.5 
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: nkl-cluster2-https
  selector:
    app: nginx-ingress
