apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkl-deployment
  namespace: nkl
  labels:
    app: nkl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkl
  template:
    metadata:
      labels:
        app: nkl
    spec:
      containers:
        - name: nginx-k8s-edge-controller
          image: ciroque/nginx-k8s-edge-controller:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 51031
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 2
      serviceAccountName: nginx-k8s-edge-controller
