apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-resource-get-watch-list
  namespace: nlk
rules:
  - apiGroups:
        - ""
    resources: ["services", "nodes", "configmaps"]
    verbs: ["get", "watch", "list"]
