# NKL Nodeport Service file
# NodePort name must be in the format of
# nkl-<upstream-block-name>
# Chris Akker, Jan 2023
#
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nkl-nginx-lb-http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: nkl-nginx-lb-https
  selector:
    app: nginx-ingress

